
export const menuJson =[

        {"name":"首页概况","vueUrl":"general/index.vue","routerUrl":"general"},
        {"name":"展示管理","vueUrl":"show/showManage.vue","routerUrl":"showManage"},
        {"name":"文章管理","vueUrl":"media/articleManage.vue","routerUrl":"articleManage"},
        {"name":"用户管理","vueUrl":"user/userManage.vue","routerUrl":"userManage"},
        {"name":"用户积分","vueUrl":"user/userIntegral.vue","routerUrl":"userIntegral"},
        {"name":"预留信息","vueUrl":"user/reservedInfo.vue","routerUrl":"reservedInfo"},
        {"name":"信用体系","vueUrl":"user/userCredit.vue","routerUrl":"userCredit"},
        {"name":"发布项目","vueUrl":"project/projPublish.vue","routerUrl":"projPublish"},
        {"name":"募集管理","vueUrl":"project/collectManage.vue","routerUrl":"collectManage"},
        {"name":"项目列表","vueUrl":"project/projectList.vue","routerUrl":"projectList"},
        {"name":"投资列表","vueUrl":"project/investList.vue","routerUrl":"investList"},
        {"name":"还款列表","vueUrl":"project/RepayList.vue","routerUrl":"RepayList"},
        {"name":"待收列表","vueUrl":"project/dueinList.vue","routerUrl":"dueinList"},
        {"name":"逾期列表","vueUrl":"project/overdueList.vue","routerUrl":"overdueList"},
        {"name":"发布待审","vueUrl":"check/checkPublish.vue","routerUrl":"checkPublish"},
        {"name":"满标复审","vueUrl":"check/reCheck.vue","routerUrl":"reCheck"},
        {"name":"偿还统计","vueUrl":"static/repayStat.vue","routerUrl":"repayStat"},
        {"name":"项目统计","vueUrl":"static/projectStatist.vue","routerUrl":"projectStatist"},
        {"name":"优惠规则","vueUrl":"activity/discountsRule.vue","routerUrl":"discountsRule"},
        {"name":"活动管理","vueUrl":"activity/activityManage.vue","routerUrl":"activityManage"},
        {"name":"优惠列表","vueUrl":"activity/discountsList.vue","routerUrl":"discountsList"},
        {"name":"用户资产","vueUrl":"user/userPropt.vue","routerUrl":"userPropt"},
        {"name":"用户银行卡","vueUrl":"user/userBankcard.vue","routerUrl":"userBankcard"},
        {"name":"资金流水","vueUrl":"property/propFlow.vue","routerUrl":"propFlow"},
        {"name":"充值明细","vueUrl":"property/rechargeRecord.vue","routerUrl":"rechargeRecord"},
        {"name":"提现明细","vueUrl":"property/drawRecord.vue","routerUrl":"drawRecord"},
        {"name":"订单管理","vueUrl":"order/orderManagement.vue","routerUrl":"orderManagement"},
        {"name":"后台用户管理","vueUrl":"backstage/adminManage.vue","routerUrl":"adminManage"},
        {"name":"用户组/权限","vueUrl":"backstage/permission.vue","routerUrl":"permission"},
        {"name":"操作记录","vueUrl":"backstage/operateRecord.vue","routerUrl":"operateRecord"},
        {"name":"系统字段","vueUrl":"system/argument.vue","routerUrl":"argument"},
        {"name":"菜单管理","vueUrl":"system/menus.vue","routerUrl":"menus"},
        {"name":"通用数据","vueUrl":"system/commom.vue","routerUrl":"commom"},
        {"name":"提示语","vueUrl":"system/tips.vue","routerUrl":"tips"},
        {"name":"模板管理","vueUrl":"info/infoTemplate.vue","routerUrl":"infoTemplate"},
        {"name":"发送记录","vueUrl":"info/sendRecord.vue","routerUrl":"sendRecord"},
        {"vueUrl":"show/showAdd.vue","routerUrl":"showAdd","name":"添加展示"},
        {"vueUrl":"media/articleAdd.vue","routerUrl":"articleAdd","name":"添加文章",},
        {"vueUrl":"user/userMessage.vue","routerUrl":"userMessage","name":"发起资料"},
        {"vueUrl":"grade/integralDetail.vue","routerUrl":"integralDetail","name":"积分明细",},
        {"vueUrl":"user/creditDetail.vue","routerUrl":"creditDetail","name":"信用明细"},
        {"vueUrl":"project/projAdd.vue","routerUrl":"projAdd","name":"新建项目",},
        {"vueUrl":"activity/addRule.vue","routerUrl":"addRule","name":"添加规则"},
        {"vueUrl":"activity/addActivitye.vue","routerUrl":"addActivitye","name":"添加活动"},
        {"vueUrl":"activity/actGrant.vue","routerUrl":"actGrant","name":"添加发放"},
        {"vueUrl":"activity/FinancialStatistics.vue","routerUrl":"FinancialStatistics","name":"财务统计"},
        {"vueUrl":"activity/TenderStatistical.vue","routerUrl":"TenderStatistical","name":"投标统计"},
        {"vueUrl":"activity/UserStatistics.vue","routerUrl":"UserStatistics","name":"用户统计"},
        {"vueUrl":"statistical/OperationStatistics.vue","routerUrl":"OperationStatistics","name":"运营统计"},
        {"vueUrl":"grade/gradeRule.vue","routerUrl":"gradeRule","name":"积分规则"},
        {"name":"问卷调查","vueUrl":"media/questionSurvey.vue","routerUrl":"questionSurvey"},
        {"name":"活动标","vueUrl":"mark/activityMark.vue","routerUrl":"activityMark"},
        {"name":"新建活动标","vueUrl":"mark/activityMarkAdd.vue","routerUrl":"activityMarkAdd"},
        {"name":"活动标投资记录","vueUrl":"mark/activityInvestmentRecord.vue","routerUrl":"activityInvestmentRecord"},
        {"name":"抽奖管理","vueUrl":"lottery/lotteryManagement.vue","routerUrl":"lotteryManagement"},
        {"name":"抽奖记录","vueUrl":"lottery/luckyDraw.vue","routerUrl":"luckyDraw"},
        {"name":"礼品管理","vueUrl":"lottery/giftManagement.vue","routerUrl":"giftManagement"},
        {"name":"添加礼品管理","vueUrl":"lottery/giftManagementAdd.vue","routerUrl":"giftManagementAdd"},
        {"name":"提现审核","vueUrl":"check/withdrawCheck.vue","routerUrl":"withdrawCheck"},



]
